// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MPP_MoveRouteEX","status":true,"description":"移動ルートに関するコマンド詰め合わせ。","parameters":{}},
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"GALV_LayerGraphics","status":true,"description":"(v.2.0) Create graphic layers for parallax mapping, fog, etc. View the 'Help' document for plugin commands and info.","parameters":{"Tile Size":"48"}},
{"name":"SmartPath","status":true,"description":"イベントもしくはプレイヤーに、高度な経路探索を提供します。","parameters":{}},
{"name":"PANDA_EndlessShake","status":true,"description":"画面のシェイクを永続的にできるようにします。","parameters":{}},
{"name":"RegionBase","status":true,"description":"リージョンのデータベース提供します","parameters":{"regionList":"[]","terrainTagList":"[]"}},
{"name":"RandomShake","status":true,"description":"イベントコマンド「画面のシェイク」にランダムに揺らす機能を追加します。","parameters":{"SwitchNumber":"0\r"}},
{"name":"MPP_MovePos","status":true,"description":"【ver.1.0】指定座標まで自動で移動させるスクリプトの追加。","parameters":{"Search Limit":"50"}}
];
